name: Android APK Build

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up JDK for building
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Grant permissions for Gradle
      - name: Grant execute permissions for Gradle
        run: chmod +x ./gradlew

      # Build APK
      - name: Build Android APK
        run: ./gradlew assembleDebug

      # Upload APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
